"""Loader for the committed HCM/VCM corrector setpoint-channel catalogs.

Each catalog file (`hcm_channels.txt`, `vcm_channels.txt`) is a two-column
text table — `<setpoint_channel>  <max_abs_amps>` per line, `#` comments and
blanks ignored — generated by `tools/gen_corrector_channels.py` (a port of
`getname_als.m` + `alsinit.m local_maxsp`). The line order defines each
corrector's **family index**, which `CMD:STEP_CM` and the response matrix use
to address correctors.

PROVISIONAL: the SR01 device list is pending a read-only `family2dev` dump
(control-room checklist A2); the counts (96 HCM / 72 VCM) already match
`mml-audit get_family`.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class CorrectorChannel:
    """One corrector's setpoint PV channel + its hardware current limit."""
    name: str                # EPICS setpoint channel, e.g. "SR01C___HCM1___AC00"
    max_abs_amps: float      # |setpoint| clamp (amps), from local_maxsp
    family: str              # "HCM" | "VCM"
    index: int               # 0-based position in the family ordering


def load_corrector_channels(path: str | Path, family: str) -> list[CorrectorChannel]:
    """Read a corrector catalog file and return its `CorrectorChannel` list.

    `family` ("HCM"/"VCM") labels the returned channels. Each line's first two
    whitespace-separated tokens are the channel name and the max |amps|; any
    trailing `# ...` comment is ignored.

    Raises:
        FileNotFoundError: if `path` does not exist.
        ValueError: if `path` has no entries, or a line is malformed.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(
            f"Corrector channel file not found: {p} "
            f"(regenerate via tools/gen_corrector_channels.py --write pytxt/config)"
        )

    channels: list[CorrectorChannel] = []
    for lineno, raw in enumerate(p.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Drop any inline comment, then split into name + limit.
        body = line.split("#", 1)[0].split()
        if len(body) < 2:
            raise ValueError(f"{p}:{lineno}: expected '<channel> <max_amps>', got {raw!r}")
        name, max_str = body[0], body[1]
        try:
            max_abs_amps = float(max_str)
        except ValueError as exc:
            raise ValueError(f"{p}:{lineno}: bad max_amps {max_str!r}") from exc
        channels.append(
            CorrectorChannel(
                name=name,
                max_abs_amps=max_abs_amps,
                family=family,
                index=len(channels),
            )
        )

    if not channels:
        raise ValueError(f"Corrector channel file {p} contains no entries")

    return channels
